---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-web-ui
  template:
    metadata:
      labels:
        name: go-web-ui
    spec:
      containers:
      - name: go-web-ui
        image: r00tsh3ll/actionsgo-dadjoke:3a9d825
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-dadjoke
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-web-dadjoke
  template:
    metadata:
      labels:
        name: go-web-dadjoke
    spec:
      containers:
      - name: go-web-dadjoke
        image: r00tsh3ll/actionsgo-dadjoke:3a9d825
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-randombeer
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-web-randombeer
  template:
    metadata:
      labels:
        name: go-web-randombeer
    spec:
      containers:
      - name: go-web-randombeer
        image: r00tsh3ll/actionsgo-randombeer:3a9d825
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-simpsons
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-web-simpsons
  template:
    metadata:
      labels:
        name: go-web-simpsons
    spec:
      containers:
      - name: go-web-simpsons
        image: r00tsh3ll/actionsgo-simpons:3a9d825
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000