name: Push-To-Prod
on:
  push:
    branches:    
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build/Test
      run: go build -v ./...

    - name: Docker Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 

    # Build the Docker images
    #- name: Build Docker Images 
    #  run: |        
    #    $GITHUB_WORKSPACE/builder/docker-build.sh

    # Push the Docker images
    #- name: Push Docker Images 
    # run: |        
    #    $GITHUB_WORKSPACE/builder/docker-push.sh

    
    # Update Deployment Configs
    - name: Update Deployment Configs
      run: |        
        $GITHUB_WORKSPACE/builder/deploy-update.sh

    # Build the Docker images
    - name: Status Update
      run: |        
        cat $GITHUB_WORKSPACE/deployment/deployment.yaml


    - name: Commit changes # This is the step name that will be displayed in your runs
      uses: EndBug/add-and-commit@v2.1.1 # You can change this to use a specific version
      with: # See more info about inputs below
        author_name: Aly
        author_email: no@thanks.com
        message: "Deployment Update"
        path: $GITHUB_WORKSPACE/deployment/
        pattern: "*"
        force: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
